name: analog
favicon: null
layout_spectrum: 0.789200900355354
typography_spectrum: 0.2620537057518959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.46208135853521526
  lightness: 0.416968310251832
  saturation: 0.26943569513969123
  rhythmicContrast: 0.30903462576679885
purpose: []
